window.OW=[['001','Estela Living, LLC'],['002','Estela Specs 1 LLC'],['003','Estela Specs 2 LLC'],['004','Estela Specs 3 LLC'],['005','Estela Specs 4 LLC'],['006','Estela Specs 6 LLC'],['007','Estela Specs 7 LLC'],['008','Estela Specs 8 LLC'],['009','Estela Specs 9 LLC'],['100','Sabana Owner, LLC']];
window.PMS=['Michael Bedaw','Jason Bedaw','Jim Humphreys','Jon Frantz'];
function _gp(){try{return JSON.parse(localStorage.getItem('estela_permits_v3')||'[]');}catch(e){return[];}}
function _gs(p){var s=p.permitStatus||p.overallStatus||'';if(s==='co')return'co';if(s==='permitted'||s==='issued')return'permitted';if(s==='review'||s==='resubmit')return'review';if(s==='applied'||s==='submitted')return'applied';return'collecting';}
var SL={collecting:'Collecting Docs',applied:'Applied',review:'Under Review',permitted:'Permitted',co:'CO Received'};
// PM & OWNER DROPDOWNS
window._patchFields=function(){document.querySelectorAll('.info-field').forEach(function(f){var lbl=f.querySelector('.info-label'),inp=f.querySelector('input.info-input');if(!inp||inp.dataset.pf)return;var label=lbl?lbl.textContent.trim():'';if(label!=='Project Manager'&&label!=='OWNER')return;inp.dataset.pf='1';var onch=inp.getAttribute('onchange')||'',cur=inp.value,sel=document.createElement('select');sel.className='info-input';sel.style.cssText='width:100%;padding:4px 8px;border:1px solid #d1d5db;border-radius:4px;font-size:13px;background:#fff;color:#1e293b';if(label==='Project Manager'){sel.innerHTML='<option value="">Select PM...</option>'+window.PMS.map(function(pm){return'<option value="'+pm+'"'+(pm.toUpperCase()===cur.toUpperCase()?' selected':'')+'>'+pm+'</option>';}).join('');}else{sel.innerHTML='<option value="">Select owner...</option>'+window.OW.map(function(o){return'<option value="'+o[0]+'"'+(o[0]===cur?' selected':'')+'>'+o[0]+' - '+o[1]+'</option>';}).join('');}sel.addEventListener('change',function(){try{eval(onch.replace(/this\.value/g,JSON.stringify(this.value)));}catch(e){}});inp.replaceWith(sel);});};
// INLINE EXPANSION
function _expandRow(tr,community,status){var nxt=tr.nextElementSibling;while(nxt&&nxt.dataset.expandRow){var tmp=nxt.nextElementSibling;nxt.remove();nxt=tmp;}var permits=_gp().filter(function(p){return p.community===community&&_gs(p)===status;});if(!permits.length)return;var colSpan=tr.querySelectorAll('td').length||8;var exp=document.createElement('tr');exp.dataset.expandRow='1';var rows=permits.map(function(p,i){return'<tr style="background:'+(i%2===0?'#f8faff':'#eff6ff')+'"><td style="padding:7px 12px 7px 28px;font-size:11px;color:#94a3b8">'+(i+1)+'</td><td style="padding:7px 14px;font-size:13px;font-weight:600">'+(p.address||'—')+'<span style="font-size:11px;color:#94a3b8;font-weight:400;margin-left:8px">Lot '+(p.lotNumber||'—')+'</span></td><td style="padding:7px 14px;font-family:monospace;font-size:12px;color:#4f46e5">'+(p.permitNumber||'—')+'</td><td style="padding:7px 14px;font-size:12px">'+(p.model||'—')+'</td><td style="padding:7px 14px;font-size:12px">'+(p.projectManager||'—')+'</td><td style="padding:7px 14px;font-size:11px;font-weight:700;color:#7c3aed">'+(p.owner||'—')+'</td></tr>';}).join('');exp.innerHTML='<td colspan="'+colSpan+'" style="padding:0;border-bottom:3px solid #3b82f6;border-top:1px solid #bfdbfe"><div style="background:#f0f9ff;border-left:4px solid #3b82f6"><div style="padding:10px 16px;display:flex;justify-content:space-between;align-items:center"><span style="font-size:12px;font-weight:700;color:#1e40af;text-transform:uppercase;letter-spacing:.5px">'+community+' · '+SL[status]+' · '+permits.length+' permits</span><button onclick="var r=this.closest('tr');var n=r.nextElementSibling;while(n&&n.dataset.expandRow){var t=n.nextElementSibling;n.remove();n=t};" style="background:none;border:1px solid #bfdbfe;border-radius:4px;cursor:pointer;color:#64748b;font-size:12px;padding:2px 8px">✕ Close</button></div><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr style="background:#dbeafe"><th style="padding:7px 28px;text-align:left;font-size:10px;font-weight:700;color:#1e40af">#</th><th style="padding:7px 14px;text-align:left;font-size:10px;font-weight:700;color:#1e40af">ADDRESS / LOT</th><th style="padding:7px 14px;text-align:left;font-size:10px;font-weight:700;color:#1e40af">PERMIT #</th><th style="padding:7px 14px;text-align:left;font-size:10px;font-weight:700;color:#1e40af">MODEL</th><th style="padding:7px 14px;text-align:left;font-size:10px;font-weight:700;color:#1e40af">PM</th><th style="padding:7px 14px;text-align:left;font-size:10px;font-weight:700;color:#1e40af">OWNER</th></tr></thead><tbody>'+rows+'</tbody></table></div></div></td>';tr.insertAdjacentElement('afterend',exp);}
// BIND ALL STATUS CELLS IN COMMUNITY TABLE
window._bindTable=function(){Array.from(document.querySelectorAll('table tbody tr')).forEach(function(tr){if(tr.dataset.expandRow||tr.dataset.bound2)return;var tds=tr.querySelectorAll('td');if(tds.length<4)return;var comm=tds[0]&&tds[0].textContent.trim();if(!comm||comm==='TOTAL'||/^\d+$/.test(comm))return;tr.dataset.bound2='1';[{i:2,s:'collecting'},{i:3,s:'review'},{i:4,s:'permitted'},{i:5,s:'co'}].forEach(function(col){var td=tds[col.i];if(!td)return;var val=td.textContent.trim();if(val==='—'||val==='')return;td.style.cursor='pointer';td.title='Click to see '+val+' '+SL[col.s]+' addresses';(function(t,c,s){td.addEventListener('click',function(e){e.stopPropagation();_expandRow(t,c,s);});})(tr,comm,col.s);});});};
// SORT COLUMNS
window._addSorting=function(){var table=document.querySelector('table');if(!table||table.dataset.sortable)return;table.dataset.sortable='1';var headers=table.querySelectorAll('th');var sortable=['ADDRESS','COMMUNITY','MODEL','PM','PROJECT','STATUS','LOT'];headers.forEach(function(th,colIdx){var txt=th.textContent.trim().toUpperCase();if(!sortable.some(function(s){return txt.includes(s);}))return;th.style.cursor='pointer';th.title='Sort A→Z / Z→A';if(!th.querySelector('._arr')){var a=document.createElement('span');a._arr='1';a.style.cssText='margin-left:4px;opacity:0.4;font-size:10px';a.textContent='⇅';th.appendChild(a);}th.addEventListener('click',function(){var tbody=table.querySelector('tbody');if(!tbody)return;var rows=Array.from(tbody.querySelectorAll('tr:not([data-expand-row])'));var cur=th._dir||1;th._dir=-cur;rows.sort(function(a,b){var at=(a.querySelectorAll('td')[colIdx]||{}).textContent||'';var bt=(b.querySelectorAll('td')[colIdx]||{}).textContent||'';return at.localeCompare(bt)*cur;});tbody.querySelectorAll('[data-expand-row]').forEach(function(r){r.remove();});rows.forEach(function(r){tbody.appendChild(r);});headers.forEach(function(h){var a=h.querySelector('._arr');if(a){a.textContent='⇅';a.style.opacity='0.4';}});var myA=th.querySelector('._arr');if(myA){myA.textContent=cur===1?'↑':'↓';myA.style.opacity='1';}});});};
setInterval(function(){window._patchFields();window._bindTable();window._addSorting();},1000);