window.OW=[['001','Estela Living, LLC'],['002','Estela Specs 1 LLC'],['003','Estela Specs 2 LLC'],['004','Estela Specs 3 LLC'],['005','Estela Specs 4 LLC'],['006','Estela Specs 6 LLC'],['007','Estela Specs 7 LLC'],['008','Estela Specs 8 LLC'],['009','Estela Specs 9 LLC'],['100','Sabana Owner, LLC']];
window.PMS=['Michael Bedaw','Jason Bedaw','Jim Humphreys','Jon Frantz'];
function _gp(){try{return JSON.parse(localStorage.getItem('estela_permits_v3')||'[]');}catch(e){return[];}}
function _gs(p){var s=p.permitStatus||p.overallStatus||'';if(s==='co')return'co';if(s==='permitted'||s==='issued')return'permitted';if(s==='review'||s==='resubmit')return'review';if(s==='applied'||s==='submitted')return'applied';return'collecting';}
var SL={collecting:'Collecting Docs',applied:'Applied',review:'Under Review',permitted:'Permitted',co:'CO Received'};

// PM & OWNER DROPDOWNS
window._pf=function(){document.querySelectorAll('.info-field').forEach(function(f){var lbl=f.querySelector('.info-label'),inp=f.querySelector('input.info-input');if(!inp||inp.dataset.pf)return;var label=lbl?lbl.textContent.trim():'';if(label!=='Project Manager'&&label!=='OWNER')return;inp.dataset.pf='1';var onch=inp.getAttribute('onchange')||'',cur=inp.value,sel=document.createElement('select');sel.className='info-input';sel.style.cssText='width:100%;padding:4px 8px;border:1px solid #d1d5db;border-radius:4px;font-size:13px;background:#fff;color:#1e293b';if(label==='Project Manager'){sel.innerHTML='<option value="">Select PM...</option>'+window.PMS.map(function(pm){return'<option value="'+pm+'"'+(pm.toUpperCase()===cur.toUpperCase()?' selected':'')+'>'+pm+'</option>';}).join('');}else{sel.innerHTML='<option value="">Select owner...</option>'+window.OW.map(function(o){return'<option value="'+o[0]+'"'+(o[0]===cur?' selected':'')+'>'+o[0]+' - '+o[1]+'</option>';}).join('');}sel.addEventListener('change',function(){try{eval(onch.replace(/this\.value/g,JSON.stringify(this.value)));}catch(e){}});inp.replaceWith(sel);});};

// INLINE ADDRESS EXPANSION
function _exp(tr,com,st){var n=tr.nextElementSibling;while(n&&n.dataset.er){var t=n.nextElementSibling;n.remove();n=t;}var pp=_gp().filter(function(p){return p.community===com&&_gs(p)===st;});if(!pp.length)return;var cs=tr.querySelectorAll('td').length||8;var exp=document.createElement('tr');exp.dataset.er='1';var rows=pp.map(function(p,i){return'<tr style="background:'+(i%2===0?'#f8faff':'#eff6ff')+'"><td style="padding:7px 12px 7px 24px;font-size:11px;color:#94a3b8">'+(i+1)+'</td><td style="padding:7px 14px;font-size:13px;font-weight:600">'+(p.address||'—')+'<span style="font-size:11px;color:#94a3b8;margin-left:8px">Lot '+(p.lotNumber||'—')+'</span></td><td style="padding:7px 14px;font-family:monospace;font-size:12px;color:#4f46e5">'+(p.permitNumber||'—')+'</td><td style="padding:7px 14px;font-size:12px">'+(p.model||'—')+'</td><td style="padding:7px 14px;font-size:12px">'+(p.projectManager||'—')+'</td><td style="padding:7px 14px;font-size:11px;font-weight:700;color:#7c3aed">'+(p.owner||'—')+'</td></tr>';}).join('');exp.innerHTML='<td colspan="'+cs+'" style="padding:0;border-bottom:3px solid #3b82f6;border-top:1px solid #bfdbfe"><div style="background:#f0f9ff;border-left:4px solid #3b82f6"><div style="padding:10px 16px;display:flex;justify-content:space-between;align-items:center"><span style="font-size:12px;font-weight:700;color:#1e40af;text-transform:uppercase">'+com+' — '+SL[st]+' ('+pp.length+')</span><button onclick="var r=this.closest('[data-er]');var n=r.nextElementSibling;while(n&&n.dataset.er){var t=n.nextElementSibling;n.remove();n=t};" style="background:none;border:1px solid #bfdbfe;border-radius:4px;cursor:pointer;color:#64748b;padding:2px 8px;font-size:12px">✕ Close</button></div><table style="width:100%;border-collapse:collapse"><thead><tr style="background:#dbeafe"><th style="padding:7px 24px;text-align:left;font-size:10px;color:#1e40af">#</th><th style="padding:7px 14px;text-align:left;font-size:10px;color:#1e40af">ADDRESS / LOT</th><th style="padding:7px 14px;text-align:left;font-size:10px;color:#1e40af">PERMIT #</th><th style="padding:7px 14px;text-align:left;font-size:10px;color:#1e40af">MODEL</th><th style="padding:7px 14px;text-align:left;font-size:10px;color:#1e40af">PM</th><th style="padding:7px 14px;text-align:left;font-size:10px;color:#1e40af">OWNER</th></tr></thead><tbody>'+rows+'</tbody></table></div></td>';tr.insertAdjacentElement('afterend',exp);}

// BIND TABLE CELLS
window._bt=function(){Array.from(document.querySelectorAll('table tbody tr')).forEach(function(tr){if(tr.dataset.er||tr.dataset.b2)return;var tds=tr.querySelectorAll('td');if(tds.length<4)return;var com=tds[0]&&tds[0].textContent.trim();if(!com||com==='TOTAL'||/^\d+$/.test(com))return;tr.dataset.b2='1';[{i:2,s:'collecting'},{i:3,s:'review'},{i:4,s:'permitted'},{i:5,s:'co'}].forEach(function(col){var td=tds[col.i];if(!td||td.textContent.trim()==='—')return;td.style.cursor='pointer';td.title='Click → see addresses';(function(t,c,s){td.addEventListener('click',function(e){e.stopPropagation();_exp(t,c,s);});})(tr,com,col.s);});});};

// MULTI-SELECT + FILTER PANEL (inserts after status buttons row)
window._addFilters=function(){
  if(document.getElementById('_ef'))return;
  // Find the row with status filter buttons
  var statusBtns=Array.from(document.querySelectorAll('button')).filter(function(b){var t=b.textContent.trim();return t==='Collecting Docs'||t==='Under Review'||t==='Permitted ✓'||t==='CO ★';});
  if(!statusBtns.length)return;
  var container=statusBtns[0].closest('div')||statusBtns[0].parentElement;
  if(!container)return;
  var panel=document.createElement('div');
  panel.id='_ef';
  panel.style.cssText='padding:12px 16px;background:#f8fafc;border-radius:8px;border:1px solid #e2e8f0;margin:8px 0';
  var slist=[['collecting','Collecting Docs'],['applied','Applied'],['review','Under Review'],['permitted','Permitted'],['co','CO Received']];
  var boxes=slist.map(function(s){return'<label id="_lbl_'+s[0]+'" style="display:inline-flex;align-items:center;gap:5px;padding:5px 12px;border:2px solid #e2e8f0;border-radius:20px;cursor:pointer;font-size:12px;font-weight:600;background:#fff;margin:3px"><input type="checkbox" value="'+s[0]+'" onchange="window._msc()"> '+s[1]+'</label>';}).join('');
  panel.innerHTML='<div style="font-size:10px;font-weight:700;color:#6b7280;margin-bottom:8px;text-transform:uppercase;letter-spacing:1px">Multi-select status — updates breakdown table</div><div style="display:flex;flex-wrap:wrap;gap:4px;margin-bottom:10px" id="_mboxes">'+boxes+'</div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><button onclick="window._msv()" style="padding:6px 14px;background:#7c3aed;color:#fff;border:none;border-radius:6px;font-size:12px;font-weight:700;cursor:pointer">View List</button><button onclick="window._msp()" style="padding:6px 14px;background:#2da44e;color:#fff;border:none;border-radius:6px;font-size:12px;font-weight:700;cursor:pointer">Print</button><button onclick="document.querySelectorAll('#_mboxes input').forEach(function(i){i.checked=false});window._msc();" style="padding:6px 14px;background:#6b7280;color:#fff;border:none;border-radius:6px;font-size:12px;font-weight:700;cursor:pointer">Clear</button><span id="_mc" style="font-size:12px;color:#6b7280"></span></div>';
  container.insertAdjacentElement('afterend',panel);
};

window._msc=function(){var sel=Array.from(document.querySelectorAll('#_mboxes input:checked')).map(function(i){return i.value;});['collecting','applied','review','permitted','co'].forEach(function(k){var el=document.getElementById('_lbl_'+k);if(el){el.style.borderColor=sel.indexOf(k)>-1?'#7c3aed':'#e2e8f0';el.style.background=sel.indexOf(k)>-1?'#ede9fe':'#fff';}});var ct=document.getElementById('_mc');if(ct)ct.textContent=sel.length?_gp().filter(function(p){return sel.indexOf(_gs(p))>-1;}).length+' permits':'';};

function _showList(title,permits){var m=document.getElementById('_dm');if(m)m.remove();m=document.createElement('div');m.id='_dm';m.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:10001;display:flex;align-items:center;justify-content:center;padding:16px';var rows=permits.map(function(p,i){var bg=i%2===0?'#fff':'#f9fafb';return'<tr style="background:'+bg+'"><td style="padding:8px 12px;color:#9ca3af;font-size:11px">'+(i+1)+'</td><td style="padding:8px 12px;font-weight:600;font-size:13px">'+(p.address||'—')+'<div style="font-size:11px;color:#9ca3af">Lot '+(p.lotNumber||'—')+' · '+(p.community||'—')+'</div></td><td style="padding:8px 12px;font-family:monospace;font-size:12px;color:#4f46e5">'+(p.permitNumber||'—')+'</td><td style="padding:8px 12px;font-size:12px">'+(p.model||'—')+'</td><td style="padding:8px 12px;font-size:12px">'+(p.projectManager||'—')+'</td><td style="padding:8px 12px;font-size:11px;font-weight:700;color:#7c3aed">'+(p.owner||'—')+'</td></tr>';}).join('');m.innerHTML='<div style="background:#fff;border-radius:12px;width:100%;max-width:960px;max-height:90vh;display:flex;flex-direction:column;box-shadow:0 8px 40px rgba(0,0,0,.3)"><div style="padding:14px 20px;border-bottom:1px solid #e5e7eb;display:flex;justify-content:space-between;align-items:center;background:#f8fafc;border-radius:12px 12px 0 0;flex-shrink:0"><div><strong>'+title+'</strong> <span style="color:#6b7280;font-size:13px">('+permits.length+')</span></div><div style="display:flex;gap:8px"><button onclick="window.print()" style="padding:6px 14px;background:#7c3aed;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:12px;font-weight:600">Print</button><button onclick="document.getElementById('_dm').remove()" style="padding:6px 14px;background:#6b7280;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:12px">Close</button></div></div><div style="overflow-y:auto;flex:1"><table style="width:100%;border-collapse:collapse"><thead style="position:sticky;top:0;background:#f1f5f9"><tr><th style="padding:10px;text-align:left;border-bottom:2px solid #e2e8f0;font-size:11px">#</th><th style="padding:10px;text-align:left;border-bottom:2px solid #e2e8f0;font-size:11px">ADDRESS</th><th style="padding:10px;text-align:left;border-bottom:2px solid #e2e8f0;font-size:11px">PERMIT#</th><th style="padding:10px;text-align:left;border-bottom:2px solid #e2e8f0;font-size:11px">MODEL</th><th style="padding:10px;text-align:left;border-bottom:2px solid #e2e8f0;font-size:11px">PM</th><th style="padding:10px;text-align:left;border-bottom:2px solid #e2e8f0;font-size:11px">OWNER</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>';m.onclick=function(e){if(e.target===m)m.remove();};document.body.appendChild(m);}

window._msv=function(){var sel=Array.from(document.querySelectorAll('#_mboxes input:checked')).map(function(i){return i.value;});var f=sel.length?_gp().filter(function(p){return sel.indexOf(_gs(p))>-1;}):_gp();var lbl=sel.length?sel.map(function(s){return SL[s];}).join(' + '):'All Permits';_showList(lbl,f);};
window._msp=function(){window._msv();setTimeout(function(){window.print();},600);};

// SORT COLUMNS
window._as=function(){var tbl=document.querySelector('table');if(!tbl||tbl.dataset.s)return;tbl.dataset.s='1';tbl.querySelectorAll('th').forEach(function(th,ci){var t=th.textContent.trim().toUpperCase();if(!['ADDRESS','COMMUNITY','MODEL','PM','PROJECT','LOT','STATUS'].some(function(s){return t.includes(s);}))return;th.style.cursor='pointer';th.title='Sort A→Z / Z→A';if(!th.querySelector('._a')){var a=document.createElement('span');a.className='_a';a.style='margin-left:4px;opacity:0.4;font-size:10px';a.textContent='⇅';th.appendChild(a);}th.addEventListener('click',function(){var tb=tbl.querySelector('tbody');if(!tb)return;var rows=Array.from(tb.querySelectorAll('tr:not([data-er])'));var d=th._d||1;th._d=-d;rows.sort(function(a,b){return((a.querySelectorAll('td')[ci]||{}).textContent||'').localeCompare((b.querySelectorAll('td')[ci]||{}).textContent||'')*d;});tb.querySelectorAll('[data-er]').forEach(function(r){r.remove();});rows.forEach(function(r){tb.appendChild(r);});tbl.querySelectorAll('._a').forEach(function(a){a.textContent='⇅';a.style.opacity='0.4';});var ma=th.querySelector('._a');if(ma){ma.textContent=d===1?'↑':'↓';ma.style.opacity='1';}});});};

setInterval(function(){window._pf();window._bt();window._addFilters();window._as();},1000);